[package]
name = "rust_lib_dart"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
gluesql-core.workspace = true
memory-storage.workspace = true
serde = "1"
serde_json = "1"
tokio = { version = "1", features = [
    "rt",
    "rt-multi-thread",
    "macros",
    "sync",
] }
rust_decimal = { version = "1", features = ["serde-str"] }
flutter_rust_bridge = "=2.0.0-dev.39"
