[package]
name = "gluesql-mongo-storage"
authors = [
  "Hyoungkwan Cho <devgony@gmail.com>",
  "Taehoon Moon <taehoon.moon@outlook.com>",
]
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true
repository.workspace = true
documentation.workspace = true

[dependencies]
gluesql-core.workspace = true
utils.workspace = true

async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
futures = "0.3"
tokio = { version = "1", features = ["rt", "macros"] }
hex = "0.4"
thiserror = "1.0"
iter-enum = "1"
async-io = "1"
mongodb = "2.5.0"
bson = { version = "2.6.1", features = ["chrono-0_4"] }
chrono = { version = "0.4.26", features = ["serde", "wasmbind"] }
strum_macros = "0.24"
strum = "0.24"
rust_decimal = { version = "1", features = ["serde-str"] }

[dev-dependencies]
test-suite.workspace = true
uuid = "1"
composite-storage.workspace = true

[features]
test-mongo = []
