name: Dart

on:
  push:
    branches: [main, release-*]
    paths-ignore:
      - "docs/**"
  pull_request:
    branches: [main, release-*]
    paths-ignore:
      - "docs/**"

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Flutter actions
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"

      - name: Run build and format check
        run: |
          cd pkg/dart
          flutter analyze
          dart format --set-exit-if-changed .
          cd rust_builder/cargokit/build_tool
          flutter analyze
  test:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v4

      - uses: futureware-tech/simulator-action@v3
        with:
          model: "iPhone 14"

      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Run build and format check
        run: flutter test integration_test
